default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: # leave this blank if you're using trust authentication
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: my_app_render_production
  username: my_app_render
  password: <%= ENV['MY_APP_RENDER_DATABASE_PASSWORD'] %>
